from selenium.webdriver.common.by import By

class LocatorsUrbanRoutesPage:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    button_get_a_cab = (By.CLASS_NAME, 'button.round')
    button_comfort = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[5]')
    button_phone_number = (By.CLASS_NAME, 'np-text')
    phone_number_field = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[1]/form/div[1]/div')
    id_phone_field = (By.ID, 'phone')
    button_following = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[1]/form/div[2]/button')
    code_sms_field = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[2]/form/div[1]/div')
    button_confirm = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[2]/form/div[2]/button[1]')
    payment_method = (By.CLASS_NAME, 'pp-button.filled')
    add_card = (By.CLASS_NAME, 'pp-row.disabled')
    number_card_field = (By.CLASS_NAME, 'card-number-input')
    text_number_card_field = (By.ID, 'number')
    code_card_field = (By.CLASS_NAME, 'card-code-input')
    text_code_card_field = (By.NAME, 'code')
    body_credit_card = (By.CLASS_NAME, 'card-wrapper')
    button_add = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[2]/form/div[3]/button[1]')
    button_x = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    message_for_driver_field = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[3]/div')
    text_message_for_driver_field = (By.ID, 'comment')
    blanket_scarves_field = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]')
    add_ice_cream = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]')
    button_looking_for_taxi = (By.CSS_SELECTOR, '.smart-button')
    window_waiting_taxi = (By.CLASS_NAME, 'order-body')

